package com.levels.lrceditor;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.time.Duration;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSlider;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.lang3.ArrayUtils;

/**
 *
 * @author Leandro Valdearenas
 */
public class LRCEditor extends javax.swing.JFrame {

    // Extensions
    private final FileNameExtensionFilter LRC_EXTENSION = new FileNameExtensionFilter("Lyric File (.lrc)", "lrc");
    private final FileNameExtensionFilter MP3_EXTENSION = new FileNameExtensionFilter("MP3 File (.mp3)", "mp3");

    // Paths
    private String lrcPath;
    private String defaultPath;

    // MP3 Player
    private Mp3Player mp3Player;

    // Selected Lyric (for editing)
    private Lyric selectedLyric;

    // Default List Model for the Lyrics
    private DefaultListModel<Lyric> listModel;

    /**
     * Creates new form LRCEditor
     */
    public LRCEditor() {
        this.defaultPath = ""; // <-- /!\ Placeholder
        this.mp3Player = new Mp3Player(this);
        this.listModel = new DefaultListModel();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fchOpen = new javax.swing.JFileChooser();
        fchSave = new javax.swing.JFileChooser();
        pnl1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnOpenLrcFile = new javax.swing.JButton();
        btnSaveLRC = new javax.swing.JButton();
        tab1 = new javax.swing.JTabbedPane();
        pnlSetLyrics = new javax.swing.JPanel();
        lblSetLyrics = new javax.swing.JLabel();
        scrTxaLyrics = new javax.swing.JScrollPane();
        txaLyrics = new javax.swing.JTextArea();
        pnlEditLyrics = new javax.swing.JPanel();
        scrLyrics = new javax.swing.JScrollPane();
        lstLyrics = new javax.swing.JList<>();
        txtTimestamp = new javax.swing.JTextField();
        txtLyric = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        pnlSong = new javax.swing.JPanel();
        sldSong = new javax.swing.JSlider();
        lblSongLength = new javax.swing.JLabel();
        btnOpenMp3File = new javax.swing.JButton();
        btnPlaySong = new javax.swing.JButton();
        btnPauseSong = new javax.swing.JButton();
        mnuBar = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniNew = new javax.swing.JMenuItem();
        mniOpen = new javax.swing.JMenuItem();
        sprMnuFile = new javax.swing.JPopupMenu.Separator();
        mniSave = new javax.swing.JMenuItem();
        mniSaveAs = new javax.swing.JMenuItem();
        mnuTools = new javax.swing.JMenu();
        mniTimestamps = new javax.swing.JMenuItem();
        mnuPreferences = new javax.swing.JMenu();

        fchOpen.setBackground(pnl1.getBackground());
        fchOpen.setCurrentDirectory(new File(defaultPath));

        fchSave.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        fchSave.setBackground(pnl1.getBackground());
        fchSave.setCurrentDirectory(new File(defaultPath));
        fchSave.setDialogTitle("Save your LRC file as");
        fchSave.setFileFilter(LRC_EXTENSION);
        fchSave.setSelectedFile(new File(".lrc"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl1.setBackground(new java.awt.Color(133, 192, 255));
        pnl1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitle.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 49, 100));
        lblTitle.setText("LeVel's LRC Editor");

        btnOpenLrcFile.setBackground(new java.awt.Color(147, 228, 255));
        btnOpenLrcFile.setForeground(new java.awt.Color(0, 107, 149));
        btnOpenLrcFile.setText("Open LRC File");
        btnOpenLrcFile.setToolTipText("Open a pre-existing .lrc file to start editing");
        btnOpenLrcFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenLrcFileActionPerformed(evt);
            }
        });

        btnSaveLRC.setBackground(new java.awt.Color(248, 255, 130));
        btnSaveLRC.setToolTipText("Save the .lrc file");
        btnSaveLRC.setEnabled(false);
        btnSaveLRC.setLabel("Save LRC File");
        btnSaveLRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveLRCActionPerformed(evt);
            }
        });

        tab1.setBackground(pnl1.getBackground());
        tab1.setForeground(lblTitle.getForeground());
        tab1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tab1StateChanged(evt);
            }
        });

        pnlSetLyrics.setBackground(new java.awt.Color(246, 86, 181));

        lblSetLyrics.setForeground(new java.awt.Color(243, 243, 243));
        lblSetLyrics.setText("Insert your lyrics below, without timestamp.");

        scrTxaLyrics.setBackground(txaLyrics.getForeground());
        scrTxaLyrics.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        scrTxaLyrics.setForeground(pnlSetLyrics.getBackground());

        txaLyrics.setBackground(new java.awt.Color(101, 0, 82));
        txaLyrics.setColumns(20);
        txaLyrics.setForeground(new java.awt.Color(255, 192, 208));
        txaLyrics.setRows(5);
        scrTxaLyrics.setViewportView(txaLyrics);

        javax.swing.GroupLayout pnlSetLyricsLayout = new javax.swing.GroupLayout(pnlSetLyrics);
        pnlSetLyrics.setLayout(pnlSetLyricsLayout);
        pnlSetLyricsLayout.setHorizontalGroup(
            pnlSetLyricsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSetLyricsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSetLyricsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrTxaLyrics, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                    .addGroup(pnlSetLyricsLayout.createSequentialGroup()
                        .addComponent(lblSetLyrics)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlSetLyricsLayout.setVerticalGroup(
            pnlSetLyricsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSetLyricsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSetLyrics)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrTxaLyrics, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab1.addTab("Set Lyrics", pnlSetLyrics);

        pnlEditLyrics.setBackground(new java.awt.Color(89, 148, 255));

        scrLyrics.setBackground(new java.awt.Color(12, 86, 124));
        scrLyrics.setForeground(new java.awt.Color(93, 124, 225));

        lstLyrics.setBackground(new java.awt.Color(11, 116, 185));
        lstLyrics.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lstLyrics.setForeground(new java.awt.Color(255, 217, 243));
        lstLyrics.setModel(listModel);
        lstLyrics.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstLyrics.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstLyricsValueChanged(evt);
            }
        });
        scrLyrics.setViewportView(lstLyrics);

        txtTimestamp.setToolTipText("Current line's timestamp, formatted: [00:00.000]");

        txtLyric.setToolTipText("Current line");

        btnSave.setBackground(new java.awt.Color(47, 255, 115));
        btnSave.setForeground(new java.awt.Color(0, 114, 29));
        btnSave.setText("Save");
        btnSave.setToolTipText("Save the line in the provided timestamp. (If the timestamp already exists, the line will be replaced.)");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(218, 0, 57));
        btnDelete.setForeground(new java.awt.Color(255, 222, 222));
        btnDelete.setText("Delete");
        btnDelete.setToolTipText("Delete the selected line.");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditLyricsLayout = new javax.swing.GroupLayout(pnlEditLyrics);
        pnlEditLyrics.setLayout(pnlEditLyricsLayout);
        pnlEditLyricsLayout.setHorizontalGroup(
            pnlEditLyricsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditLyricsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimestamp, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLyric, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap())
            .addGroup(pnlEditLyricsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEditLyricsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrLyrics, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlEditLyricsLayout.setVerticalGroup(
            pnlEditLyricsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditLyricsLayout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addGroup(pnlEditLyricsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLyric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimestamp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete)
                    .addComponent(btnSave))
                .addContainerGap())
            .addGroup(pnlEditLyricsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEditLyricsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrLyrics, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addGap(38, 38, 38)))
        );

        tab1.addTab("Edit Lyrics", pnlEditLyrics);

        pnlSong.setBackground(new java.awt.Color(82, 173, 255));
        pnlSong.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sldSong.setBackground(new java.awt.Color(34, 92, 137));
        sldSong.setForeground(new java.awt.Color(182, 24, 143));
        sldSong.setValue(0);
        sldSong.setEnabled(false);
        sldSong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sldSongMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sldSongMouseReleased(evt);
            }
        });

        lblSongLength.setForeground(new java.awt.Color(8, 6, 65));
        lblSongLength.setText("00:00");

        btnOpenMp3File.setBackground(btnPlaySong.getBackground());
        btnOpenMp3File.setForeground(btnPlaySong.getForeground());
        btnOpenMp3File.setText("Open MP3 File");
        btnOpenMp3File.setToolTipText("Open a .mp3 file to play it while editing");
        btnOpenMp3File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenMp3FileActionPerformed(evt);
            }
        });

        btnPlaySong.setBackground(new java.awt.Color(40, 99, 156));
        btnPlaySong.setForeground(new java.awt.Color(255, 195, 230));
        btnPlaySong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play.png"))); // NOI18N
        btnPlaySong.setEnabled(false);
        btnPlaySong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaySongActionPerformed(evt);
            }
        });

        btnPauseSong.setBackground(new java.awt.Color(40, 99, 156));
        btnPauseSong.setForeground(new java.awt.Color(255, 195, 230));
        btnPauseSong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stop.png"))); // NOI18N
        btnPauseSong.setEnabled(false);
        btnPauseSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseSongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSongLayout = new javax.swing.GroupLayout(pnlSong);
        pnlSong.setLayout(pnlSongLayout);
        pnlSongLayout.setHorizontalGroup(
            pnlSongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOpenMp3File, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnPlaySong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPauseSong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sldSong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSongLength)
                .addContainerGap())
        );
        pnlSongLayout.setVerticalGroup(
            pnlSongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPauseSong)
                    .addGroup(pnlSongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sldSong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSongLength)
                        .addComponent(btnOpenMp3File)
                        .addComponent(btnPlaySong)))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 331, Short.MAX_VALUE)
                .addComponent(btnOpenLrcFile)
                .addGap(18, 18, 18)
                .addComponent(btnSaveLRC)
                .addContainerGap())
            .addComponent(pnlSong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tab1))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnSaveLRC)
                    .addComponent(btnOpenLrcFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 338, Short.MAX_VALUE)
                .addComponent(pnlSong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl1Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(tab1)
                    .addGap(40, 40, 40)))
        );

        tab1.getAccessibleContext().setAccessibleName("tab1");

        mnuFile.setText("File");

        mniNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniNew.setText("New File");
        mniNew.setToolTipText("Start over from a new file");
        mniNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNewActionPerformed(evt);
            }
        });
        mnuFile.add(mniNew);

        mniOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniOpen.setText("Open File...");
        mniOpen.setToolTipText("Open a pre-existing file to start editing");
        mniOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniOpenActionPerformed(evt);
            }
        });
        mnuFile.add(mniOpen);
        mnuFile.add(sprMnuFile);

        mniSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniSave.setText("Save File");
        mniSave.setToolTipText("Save changes to .lrc file");
        mniSave.setEnabled(false);
        mniSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSaveActionPerformed(evt);
            }
        });
        mnuFile.add(mniSave);

        mniSaveAs.setText("Save As...");
        mniSaveAs.setToolTipText("Save as a new .lrc file");
        mniSaveAs.setEnabled(false);
        mniSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSaveAsActionPerformed(evt);
            }
        });
        mnuFile.add(mniSaveAs);

        mnuBar.add(mnuFile);

        mnuTools.setText("Tools");
        mnuTools.setToolTipText("");

        mniTimestamps.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniTimestamps.setText("Change All Timestamps");
        mniTimestamps.setToolTipText("Move all timestamps a specified amount of time (forward or backward)");
        mniTimestamps.setEnabled(false);
        mniTimestamps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTimestampsActionPerformed(evt);
            }
        });
        mnuTools.add(mniTimestamps);

        mnuBar.add(mnuTools);

        mnuPreferences.setText("Preferences");
        mnuPreferences.setEnabled(false);
        mnuBar.add(mnuPreferences);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // OPEN LRC FILE (BUTTON)
    private void btnOpenLrcFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenLrcFileActionPerformed
        openLrcFile();
    }//GEN-LAST:event_btnOpenLrcFileActionPerformed

    // CHANGE LYRIC SELECTION
    private void lstLyricsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstLyricsValueChanged
        if (!evt.getValueIsAdjusting()) {
            selectLyric(this.lstLyrics.getSelectedValue());
        }
    }//GEN-LAST:event_lstLyricsValueChanged

    // DELETE SELECTED LYRIC
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            // Remove selected lyric
            listModel.removeElement(selectedLyric);
            this.lstLyrics.clearSelection();
            resetSaveButtons();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid timestamp. Try again. (" + e.getMessage() + ")");
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "The timestamp is invalid. Make sure it looks like the next example: [00:00.000]");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    // SAVE LINE (BUTTON)
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            Lyric savedLyric = new Lyric(stringToDuration(txtTimestamp.getText()), txtLyric.getText());
            if (!listModel.isEmpty()) {
                // Loop through listModel's lyrics
                for (int i = 0; i < listModel.size(); i++) {
                    Lyric lyric = listModel.getElementAt(i);

                    // If timestamp is null
                    if (lyric.getTimestamp() == null) {
                        if (lyric.getLyric().equals(savedLyric.getLyric())) {
                            // If lyric is the same, replace timestamp
                            lyric.setTimestamp(savedLyric.getTimestamp());
                            break;
                        }
                    } else {
                        int difference = lyric.getTimestamp().compareTo(savedLyric.getTimestamp());

                        // If timestamp is the same, replace lyric
                        if (difference == 0) {
                            lyric.setLyric(savedLyric.getLyric());
                            break;
                        }

                        // If inserted timestamp is smaller, add the lyric in that position
                        if (difference > 0) {
                            listModel.add(i, savedLyric);
                            break;
                        }
                    }

                    // If there is nothing after, add the lyric at the end
                    if (i + 1 == listModel.size()) {
                        listModel.addElement(savedLyric);
                    }
                }
                this.lstLyrics.clearSelection();
            } else {
                listModel.addElement(savedLyric);
            }

            // Reset save buttons and other functions
            resetSaveButtons();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid timestamp. Try again. (" + e.getMessage() + ")");
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "The timestamp is invalid. Make sure it looks like the next example: [00:00.000]");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    // SAVE LRC FILE (BUTTON)
    private void btnSaveLRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveLRCActionPerformed
        saveFile();
    }//GEN-LAST:event_btnSaveLRCActionPerformed

    // OPEN "CHANGE TIMESTAMPS" POPUP MENU (MENU ITEM)
    private void mniTimestampsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTimestampsActionPerformed
        String value = JOptionPane.showInputDialog("Move all timestamps by an amount of time (+/-)");
        try {
            // Remove all brackets
            value = trimBrackets(value);

            // Get sign if provided
            boolean addition = true;
            char sign = value.charAt(0);
            if (sign == '+' || sign == '-') {
                // Remove sign from string
                value = value.substring(1).strip();
                addition = sign == '+';
            }

            // Get timestamp
            Duration timestamp = stringToDuration(value);

            // Check if any timestamp would be negative
            if (!addition) {
                for (int i = 0; i < listModel.size(); i++) {
                    Lyric lyric = listModel.getElementAt(i);
                    if (lyric.getTimestamp().compareTo(timestamp) < 0) {
                        throw new NegativeTimestampException("Operation results in negative timestamp: "
                                + Lyric.timestampToString(lyric.getTimestamp()) + " - "
                                + Lyric.timestampToString(timestamp) + " = "
                                + Lyric.timestampToString(lyric.getTimestamp().minus(timestamp)));
                    }
                }
            }

            // Perform addition/substraction
            for (int i = 0; i < listModel.size(); i++) {
                listModel.getElementAt(i).moveTimestamp(timestamp, addition);
            }

            // Update lyrics list UI
            this.lstLyrics.updateUI();

        } catch (NegativeTimestampException e) {
            JOptionPane.showMessageDialog(null, "Invalid substraction, make sure there are no timestamps smaller than the inserted value.\n" + e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Inserted value is invalid. Make sure it's a valid timestamp operation, like: +00:00.000");
        }
    }//GEN-LAST:event_mniTimestampsActionPerformed

    // SAVE LRC FILE (MENU ITEM)
    private void mniSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSaveActionPerformed
        saveFile();
    }//GEN-LAST:event_mniSaveActionPerformed

    // OPEN LRC FILE (MENU ITEM)
    private void mniOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniOpenActionPerformed
        openLrcFile();
    }//GEN-LAST:event_mniOpenActionPerformed

    // NEW FILE (MENU ITEM)
    private void mniNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNewActionPerformed
        resetLrc();
    }//GEN-LAST:event_mniNewActionPerformed

    // SAVE FILE AS (MENU ITEM)
    private void mniSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSaveAsActionPerformed
        try {
            saveFileAs();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while saving file: " + e.getMessage());
        }
    }//GEN-LAST:event_mniSaveAsActionPerformed

    // CHANGE TABS
    private void tab1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tab1StateChanged
        switch (tab1.getSelectedIndex()) {
            case 0 ->
                // Change to first tab
                setTxaTextFromList();
            case 1 ->
                // Change to second tab
                setListLyricsFromTxa();
        }
    }//GEN-LAST:event_tab1StateChanged

    // OPEN SONG FILE (BUTTON)
    private void btnOpenMp3FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenMp3FileActionPerformed
        openSongFile();
    }//GEN-LAST:event_btnOpenMp3FileActionPerformed

    // PLAY SONG (BUTTON)
    private void btnPlaySongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaySongActionPerformed
        playSong();
    }//GEN-LAST:event_btnPlaySongActionPerformed

    // PAUSE SONG (BUTTON)
    private void btnPauseSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseSongActionPerformed
        pauseSong();
    }//GEN-LAST:event_btnPauseSongActionPerformed

    // MOUSE PRESS PLAYBACK SLIDER
    private void sldSongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldSongMousePressed
        // Pause without setting is playing as false, so it can resume after adjusting
        this.mp3Player.pauseSong();
    }//GEN-LAST:event_sldSongMousePressed

    // MOUSE RELEASE PLAYBACK SLIDER
    private void sldSongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldSongMouseReleased
        // Get requested frame
        JSlider source = (JSlider) evt.getSource();
        int frame = source.getValue();

        // Update mp3 player's current frame and millis
        this.mp3Player.setCurrentFrame(frame);
        this.mp3Player.setCurrentMillis((int) (frame / (2.08 * this.mp3Player.getSong().getFrameRatePerMillis())));

        // If song was playing before sliding
        if (this.mp3Player.wasPlaying()) {
            // Resume the song
            this.mp3Player.playSong();
            this.btnPlaySong.setEnabled(false);
            this.btnPauseSong.setEnabled(true);
        }
    }//GEN-LAST:event_sldSongMouseReleased

    // Select and play MP3 file
    private void openSongFile() {
        try {
            this.fchOpen.setDialogTitle("Select MP3 file");
            this.fchOpen.setFileFilter(MP3_EXTENSION);
            this.mp3Player.loadSong(new Song(selectFile()));
            this.lblSongLength.setText(this.mp3Player.getSong().getLength());

        } catch (TaskCancelledException e) {
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problem accessing file: " + e.getMessage());
        }
    }

    // Select and read LRC file
    private void openLrcFile() {
        try {
            this.fchOpen.setDialogTitle("Select LRC file");
            this.fchOpen.setFileFilter(LRC_EXTENSION);
            this.lrcPath = selectFile();

            // Open edit tab
            tab1.setSelectedIndex(1);

            // Clear the list and read the file
            this.listModel.clear();
            readLrcFile(this.lrcPath);
            resetSaveButtons();

        } catch (TaskCancelledException e) {
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Problem accessing file: " + e.getMessage());
        }
    }

    // Select file and return its absolute path
    private String selectFile() throws IOException, TaskCancelledException {
        int returnVal = fchOpen.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            // Return selected file's absolute path
            File file = fchOpen.getSelectedFile();
            return file.getAbsolutePath();
        } else {
            // File chooser was cancelled/discarded
            throw new TaskCancelledException();
        }
    }

    // Read LRC file and extract lyrics from it
    private void readLrcFile(String path) throws FileNotFoundException {
        File myObj = new File(path);
        try (Scanner myReader = new Scanner(myObj)) {
            while (myReader.hasNextLine()) {
                String data = myReader.nextLine();

                // Skip empty lines
                if (data.trim().isEmpty()) {
                    continue;
                }

                // Only add item to list if it's a timestamp
                if (Character.isDigit(data.charAt(1))) {
                    Lyric lyric = stringToLyric(data);
                    listModel.addElement(lyric);
                    continue;
                }

                // Save song length if declared
                if (data.startsWith("[length: ")) {
                    this.mp3Player.addSongLength(data.split("\\[length:", 2)[1].split("\\]", 2)[0].strip());
                }
            }
        }
    }

    // Reset file path, lyrics, tabs, text areas, selected lyric, buttons.
    private void resetLrc() {
        this.lrcPath = null;
        this.listModel.clear();
        this.tab1.setSelectedIndex(0);
        this.txaLyrics.setText("");
        selectLyric(null);
        resetSaveButtons();
    }

    // Save file
    private void saveFile() {
        try {
            // If lrcPath is null, save as new file
            if (this.lrcPath == null) {
                // Get current song's path
                String songPath = this.mp3Player.getSong().getAbsolutePath();

                // If songPath isn't null
                if (songPath != null) {
                    // Ask the user for confirmation
                    int confirmResult = JOptionPane.showConfirmDialog(null, "Save LRC file with song's filename?");

                    // If user confirmed, set songPath as lrcPath (with .lrc extension) and save
                    if (confirmResult == JOptionPane.YES_OPTION) {
                        // Set lrcPath to current song's path and name (but with lrc extension)
                        this.lrcPath = songPath.replace(".mp3", ".lrc");

                        // Save .lrc file
                        saveToFile(this.lrcPath);

                        // Return
                        return;
                    }
                }

                // Save as new file
                saveFileAs();
            } else {
                // Overwrite file
                saveToFile(this.lrcPath);
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "An error occurred while saving file: " + e.getMessage());
        }
    }

    // Save file as...
    private void saveFileAs() throws IOException {
        int option = fchSave.showSaveDialog(null);
        if (option == JFileChooser.APPROVE_OPTION) {
            // Get selected file and its absolute path
            File file = fchSave.getSelectedFile();
            this.lrcPath = file.getAbsolutePath();

            // Save file
            saveToFile(this.lrcPath);

            // Dialog
            JOptionPane.showMessageDialog(null, "File Saved as: " + file.getName());
        }
    }

    // Save information to file
    private void saveToFile(String path) throws IOException {
        String length = this.mp3Player.getSong().getLength();

        if (length == null) {
            // If length is null, use last lyric's timestamp
            length = trimBrackets(Lyric.timestampToString(listModel.lastElement().getTimestamp()));
        }

        try (FileWriter myWriter = new FileWriter(path)) {
            // Write length and tool
            myWriter.write("[length: " + length + "]\n[tool: LeVel's LRC Editor]\n");

            // Write lyrics with timestamps
            for (int i = 0; i < this.listModel.size(); i++) {
                myWriter.write(this.listModel.elementAt(i).toLrcString());
            }
        }
    }

    // Select lyric and reset Text Inputs and Delete Button
    private void selectLyric(Lyric lyric) {
        // If lyric is null, create new lyric
        if (lyric == null) {
            lyric = new Lyric();
        }

        // Reset fields
        this.selectedLyric = lyric;
        this.txtTimestamp.setText(Lyric.timestampToString(this.selectedLyric.getTimestamp()));
        this.txtLyric.setText(this.selectedLyric.getLyric());
        this.btnDelete.setEnabled(lyric.getTimestamp() != null);
    }

    // Enable/disable save buttons and other operations
    private void resetSaveButtons() {
        // Enable if list has items, otherwise disable
        boolean enabled = !listModel.isEmpty();

        // Disable if any timestamp is null
        if (enabled) {
            for (var l : listModel.toArray()) {
                if (((Lyric) l).getTimestamp() == null) {
                    enabled = false;
                    break;
                }
            }
        }

        // Enable/disable elements
        this.btnSaveLRC.setEnabled(enabled);
        this.mniSave.setEnabled(enabled);
        this.mniSaveAs.setEnabled(enabled);
        this.mniTimestamps.setEnabled(enabled);
    }

    // Play song and enable pause button
    private void playSong() {
        this.mp3Player.playSong();

        // Enable/disable pause and play buttons
        this.btnPlaySong.setEnabled(false);
        this.btnPauseSong.setEnabled(true);
    }

    // Pause song and enable play button
    private void pauseSong() {
        this.mp3Player.hitPauseSong();

        // Enable/disable pause and play buttons
        this.btnPlaySong.setEnabled(true);
        this.btnPauseSong.setEnabled(false);
    }

    // Set text area text from listModel values
    private void setTxaTextFromList() {
        // Reset text area
        txaLyrics.setText("");

        // Loop through listModel and write lines into text area
        for (int i = 0; i < this.listModel.size(); i++) {
            var line = this.listModel.elementAt(i).getLyric() + (i + 1 < this.listModel.size() ? "\n" : "");
            txaLyrics.setText(txaLyrics.getText().concat(line));
        }
    }

    // Set listModel values from text area
    private void setListLyricsFromTxa() {
        // Get text from text area
        String text = txaLyrics.getText();

        // In case last line is empty, add it to listModel as line break
        if (!text.isBlank() && text.endsWith("")) {
            text += "\n";
        }

        // Save current lyrics and get text area's lines
        var savedLyrics = listModel.toArray();
        var lines = text.lines().toList();

        // Clear List Model
        listModel.clear();

        // Loop through text area's lines
        for (var line : lines) {
            // Create new Lyric with this line
            var newLyric = new Lyric(null, line);

            // Loop through saved lyrics
            for (int i = 0; i < savedLyrics.length; i++) {
                // If saved lyric has same text as new lyric
                if (((Lyric) savedLyrics[i]).getLyric().equals(line)) {
                    // Set new lyric's timestamp from saved lyric
                    newLyric.setTimestamp(((Lyric) savedLyrics[i]).getTimestamp());

                    // Remove saved lyric from array
                    savedLyrics = ArrayUtils.remove(savedLyrics, i);

                    // Break inner loop
                    break;
                }
            }

            // Add new lyric to listModel
            listModel.addElement(newLyric);
        }

        // Reset buttons and other functions
        resetSaveButtons();

        // Reset selected lyric and text inputs
        selectLyric(null);
    }

    // Convert String to Lyric
    private Lyric stringToLyric(String fullLyric) throws NumberFormatException {
        // Get timestamp without brackets
        Duration timestamp = stringToDuration(fullLyric.split("\\]", 2)[0]);

        // Get everything after first close bracket
        String lyric = fullLyric.split("\\]", 2)[1].strip();

        return new Lyric(timestamp, lyric);
    }

    // Convert String to Duration
    private Duration stringToDuration(String string) throws NumberFormatException {
        String[] fullTime = trimBrackets(string).split("[:.]");
        Duration timestamp = Duration
                .ofMinutes(Integer.parseInt(fullTime[0]))
                .plusSeconds(Integer.parseInt(fullTime[1]))
                .plusMillis(Integer.parseInt(fullTime[2]));

        return timestamp;
    }

    // Trim brackets
    private String trimBrackets(String string) {
        return string.replaceAll("[\\[\\]]", "");
    }

    // Set song slider's max size
    public void setSldSongMaximum(int maximum) {
        this.sldSong.setMaximum(maximum);
    }

    // Set song slider's position
    public void setSldSongValue(int value) {
        this.sldSong.setValue(value);
    }

    // Enable mp3 player buttons and slider
    public void enableMp3PlayerButtons() {
        this.btnPlaySong.setEnabled(true);
        this.btnPauseSong.setEnabled(false);
        this.sldSong.setEnabled(true);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LRCEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LRCEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LRCEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LRCEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LRCEditor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnOpenLrcFile;
    private javax.swing.JButton btnOpenMp3File;
    private javax.swing.JButton btnPauseSong;
    private javax.swing.JButton btnPlaySong;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveLRC;
    private javax.swing.JFileChooser fchOpen;
    private javax.swing.JFileChooser fchSave;
    private javax.swing.JLabel lblSetLyrics;
    private javax.swing.JLabel lblSongLength;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<Lyric> lstLyrics;
    private javax.swing.JMenuItem mniNew;
    private javax.swing.JMenuItem mniOpen;
    private javax.swing.JMenuItem mniSave;
    private javax.swing.JMenuItem mniSaveAs;
    private javax.swing.JMenuItem mniTimestamps;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuPreferences;
    private javax.swing.JMenu mnuTools;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnlEditLyrics;
    private javax.swing.JPanel pnlSetLyrics;
    private javax.swing.JPanel pnlSong;
    private javax.swing.JScrollPane scrLyrics;
    private javax.swing.JScrollPane scrTxaLyrics;
    private javax.swing.JSlider sldSong;
    private javax.swing.JPopupMenu.Separator sprMnuFile;
    private javax.swing.JTabbedPane tab1;
    private javax.swing.JTextArea txaLyrics;
    private javax.swing.JTextField txtLyric;
    private javax.swing.JTextField txtTimestamp;
    // End of variables declaration//GEN-END:variables
}
